version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - docker login --username sagar1589 --password shivganga_1589
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t practice-tukai-users-service:latest .
      - docker tag practice-tukai-users-service:latest sagar1589/practice-tukai-users-service:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push sagar1589/practice-tukai-users-service:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' practice-tukai-users sagar1589/practice-tukai-users-service:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json